-- OXX/OXXh + Brigs update for Aetherion
-- Rode no SQL Editor do Supabase depois do schema principal.

alter table public.profiles
  add column if not exists email text;

create table if not exists public.game_chat_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  sender_name text not null default 'Jogador',
  message text not null check (char_length(message) <= 220),
  region_key text default 'global',
  created_at timestamptz default now()
);

create table if not exists public.oxx_engine_events (
  id bigint generated by default as identity primary key,
  engine text not null default 'OXX',
  subsystem text not null default 'Brigs',
  level text not null default 'info',
  message text not null,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.player_test_characters (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  character_key text not null,
  active boolean default true,
  updated_at timestamptz default now(),
  unique(user_id, character_key)
);

alter table public.game_chat_messages enable row level security;
alter table public.oxx_engine_events enable row level security;
alter table public.player_test_characters enable row level security;

drop policy if exists "chat_read_all" on public.game_chat_messages;
create policy "chat_read_all" on public.game_chat_messages for select using (true);

drop policy if exists "chat_insert_authenticated" on public.game_chat_messages;
create policy "chat_insert_authenticated" on public.game_chat_messages for insert
with check (auth.uid() is not null and (user_id is null or user_id = auth.uid()));

drop policy if exists "events_admin_read" on public.oxx_engine_events;
create policy "events_admin_read" on public.oxx_engine_events for select
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists "test_characters_owner" on public.player_test_characters;
create policy "test_characters_owner" on public.player_test_characters for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.handle_aetherion_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, nickname, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nickname', split_part(new.email, '@', 1)),
    case when lower(new.email) = 'inaciooofc@gmail.com' then 'admin' else 'player' end
  )
  on conflict (id) do update set
    email = excluded.email,
    role = case when lower(excluded.email) = 'inaciooofc@gmail.com' then 'admin' else public.profiles.role end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_aetherion on auth.users;
create trigger on_auth_user_created_aetherion
after insert on auth.users
for each row execute function public.handle_aetherion_new_user();

update public.profiles
set role = 'admin', email = coalesce(email, 'inaciooofc@gmail.com')
where lower(email) = 'inaciooofc@gmail.com'
   or id in (select id from auth.users where lower(email) = 'inaciooofc@gmail.com');

insert into public.oxx_engine_events (engine, subsystem, level, message)
values ('OXX', 'migration', 'info', 'OXX/OXXh/Brigs schema installed')
on conflict do nothing;
