-- Aetherion: PNGs definitivos integrados aos itens
-- Rode depois do supabase_schema.sql e seed_data.sql

alter table public.items add column if not exists icon_url text;
alter table public.items add column if not exists visual_key text;

insert into public.items (key, name, type, rarity, icon_url, visual_key, stats, stackable) values
('espada_de_ferro','Espada de Ferro','weapon','common','/assets/items/weapons/espada_de_ferro.png','weapon_sword','{}'::jsonb,false),
('machado_de_guerra','Machado de Guerra','weapon','common','/assets/items/weapons/machado_de_guerra.png',null,'{}'::jsonb,false),
('lanca_de_cacador','Lança de Caçador','weapon','common','/assets/items/weapons/lanca_de_cacador.png',null,'{}'::jsonb,false),
('arco_de_carvalho','Arco de Carvalho','weapon','common','/assets/items/weapons/arco_de_carvalho.png',null,'{}'::jsonb,false),
('adaga_sombria','Adaga Sombria','weapon','common','/assets/items/weapons/adaga_sombria.png',null,'{}'::jsonb,false),
('martelo_dhurakar','Martelo Dhurakar','weapon','common','/assets/items/weapons/martelo_dhurakar.png',null,'{}'::jsonb,false),
('cajado_arcano','Cajado Arcano','weapon','common','/assets/items/weapons/cajado_arcano.png',null,'{}'::jsonb,false),
('foice_ritualistica','Foice Ritualística','weapon','common','/assets/items/weapons/foice_ritualistica.png',null,'{}'::jsonb,false),
('besta_de_valoria','Besta de Valoria','weapon','common','/assets/items/weapons/besta_de_valoria.png',null,'{}'::jsonb,false),
('katana_de_cinzas','Katana de Cinzas','weapon','common','/assets/items/weapons/katana_de_cinzas.png',null,'{}'::jsonb,false),
('escudo_valmorne','Escudo Valmorne','equipment','uncommon','/assets/items/armor/escudo_valmorne.png','shield_valmorne','{}'::jsonb,false),
('escudo_dhurakar','Escudo Dhurakar','equipment','uncommon','/assets/items/armor/escudo_dhurakar.png',null,'{}'::jsonb,false),
('elmo_de_ferro','Elmo de Ferro','equipment','uncommon','/assets/items/armor/elmo_de_ferro.png','helmet_iron','{}'::jsonb,false),
('peitoral_de_couro','Peitoral de Couro','equipment','uncommon','/assets/items/armor/peitoral_de_couro.png','armor_leather','{}'::jsonb,false),
('armadura_de_placas','Armadura de Placas','equipment','uncommon','/assets/items/armor/armadura_de_placas.png','armor_plate','{}'::jsonb,false),
('luvas_de_batalha','Luvas de Batalha','equipment','uncommon','/assets/items/armor/luvas_de_batalha.png',null,'{}'::jsonb,false),
('botas_de_marcha','Botas de Marcha','equipment','uncommon','/assets/items/armor/botas_de_marcha.png',null,'{}'::jsonb,false),
('capa_de_cacador','Capa de Caçador','equipment','uncommon','/assets/items/armor/capa_de_cacador.png',null,'{}'::jsonb,false),
('armadura_drakari','Armadura Drakari','equipment','uncommon','/assets/items/armor/armadura_drakari.png',null,'{}'::jsonb,false),
('manto_elarisian','Manto Elarisian','equipment','uncommon','/assets/items/armor/manto_elarisian.png','armor_leather','{}'::jsonb,false),
('anel_de_prata','Anel de Prata','accessory','uncommon','/assets/items/accessories/anel_de_prata.png',null,'{}'::jsonb,false),
('anel_de_sangue','Anel de Sangue','accessory','uncommon','/assets/items/accessories/anel_de_sangue.png',null,'{}'::jsonb,false),
('amuleto_de_eter','Amuleto de Éter','accessory','uncommon','/assets/items/accessories/amuleto_de_eter.png','aura_eter','{}'::jsonb,false),
('colar_de_ossos','Colar de Ossos','accessory','uncommon','/assets/items/accessories/colar_de_ossos.png',null,'{}'::jsonb,false),
('bracelete_de_guerra','Bracelete de Guerra','accessory','uncommon','/assets/items/accessories/bracelete_de_guerra.png',null,'{}'::jsonb,false),
('pingente_lunar','Pingente Lunar','accessory','uncommon','/assets/items/accessories/pingente_lunar.png',null,'{}'::jsonb,false),
('cinto_de_utilidades','Cinto de Utilidades','accessory','uncommon','/assets/items/accessories/cinto_de_utilidades.png',null,'{}'::jsonb,false),
('medalhao_familiar','Medalhão Familiar','accessory','uncommon','/assets/items/accessories/medalhao_familiar.png',null,'{}'::jsonb,false),
('coroa_rachada','Coroa Rachada','accessory','uncommon','/assets/items/accessories/coroa_rachada.png',null,'{}'::jsonb,false),
('broche_de_herdeiro','Broche de Herdeiro','accessory','uncommon','/assets/items/accessories/broche_de_herdeiro.png',null,'{}'::jsonb,false),
('pocao_de_cura','Poção de Cura','consumable','common','/assets/items/consumables/pocao_de_cura.png',null,'{}'::jsonb,true),
('pocao_de_mana','Poção de Mana','consumable','common','/assets/items/consumables/pocao_de_mana.png',null,'{}'::jsonb,true),
('pocao_de_stamina','Poção de Stamina','consumable','common','/assets/items/consumables/pocao_de_stamina.png',null,'{}'::jsonb,true),
('elixir_de_san','Elixir de San','consumable','common','/assets/items/consumables/elixir_de_san.png',null,'{}'::jsonb,true),
('antidoto','Antídoto','consumable','common','/assets/items/consumables/antidoto.png',null,'{}'::jsonb,true),
('frasco_de_fogo','Frasco de Fogo','consumable','common','/assets/items/consumables/frasco_de_fogo.png',null,'{}'::jsonb,true),
('oleo_de_lamina','Óleo de Lâmina','consumable','common','/assets/items/consumables/oleo_de_lamina.png',null,'{}'::jsonb,true),
('tonico_de_vitalidade','Tônico de Vitalidade','consumable','common','/assets/items/consumables/tonico_de_vitalidade.png',null,'{}'::jsonb,true),
('essencia_de_eter','Essência de Éter','consumable','common','/assets/items/consumables/essencia_de_eter.png',null,'{}'::jsonb,true),
('po_de_invisibilidade','Pó de Invisibilidade','consumable','common','/assets/items/consumables/po_de_invisibilidade.png',null,'{}'::jsonb,true),
('lanca_de_trovao','Lança de Trovão','relic','anomalous','/assets/items/relics/lanca_de_trovao.png',null,'{}'::jsonb,false),
('orbe_explosivo','Orbe Explosivo','relic','anomalous','/assets/items/relics/orbe_explosivo.png',null,'{}'::jsonb,false),
('olho_voador','Olho Voador','relic','anomalous','/assets/items/relics/olho_voador.png',null,'{}'::jsonb,false),
('guardiao_sem_alma','Guardião Sem Alma','relic','anomalous','/assets/items/relics/guardiao_sem_alma.png',null,'{}'::jsonb,false),
('nucleo_de_luz','Núcleo de Luz','relic','anomalous','/assets/items/relics/nucleo_de_luz.png',null,'{}'::jsonb,false),
('raio_de_eter','Raio de Éter','relic','anomalous','/assets/items/relics/raio_de_eter.png',null,'{}'::jsonb,false),
('coracao_de_ferro','Coração de Ferro','relic','anomalous','/assets/items/relics/coracao_de_ferro.png',null,'{}'::jsonb,false),
('oraculo_de_vidro','Oráculo de Vidro','relic','anomalous','/assets/items/relics/oraculo_de_vidro.png',null,'{}'::jsonb,false),
('chave_de_outro_mundo','Chave de Outro Mundo','relic','anomalous','/assets/items/relics/chave_de_outro_mundo.png',null,'{}'::jsonb,false),
('fragmento_da_ruptura','Fragmento da Ruptura','relic','anomalous','/assets/items/relics/fragmento_da_ruptura.png','aura_eter','{}'::jsonb,false),
('manto_da_convergencia','Manto da Convergência','sacred','sacred','/assets/items/sacred/manto_da_convergencia.png',null,'{}'::jsonb,false),
('anel_de_renascenca','Anel de Renascença','sacred','sacred','/assets/items/sacred/anel_de_renascenca.png',null,'{}'::jsonb,false),
('espada_do_monarca','Espada do Monarca','sacred','sacred','/assets/items/sacred/espada_do_monarca.png',null,'{}'::jsonb,false),
('armadura_da_santidade','Armadura da Santidade','sacred','sacred','/assets/items/sacred/armadura_da_santidade.png',null,'{}'::jsonb,false),
('pergaminho_maldito_do_escriba','Pergaminho Maldito do Escriba','sacred','sacred','/assets/items/sacred/pergaminho_maldito_do_escriba.png',null,'{}'::jsonb,false),
('calice_de_mantis','Cálice de Mantis','sacred','sacred','/assets/items/sacred/calice_de_mantis.png',null,'{}'::jsonb,false),
('lagrima_de_gan','Lágrima de Gan','sacred','sacred','/assets/items/sacred/lagrima_de_gan.png',null,'{}'::jsonb,false),
('veu_de_mirian','Véu de Mirian','sacred','sacred','/assets/items/sacred/veu_de_mirian.png',null,'{}'::jsonb,false),
('selo_de_aelyra','Selo de Aelyra','sacred','sacred','/assets/items/sacred/selo_de_aelyra.png',null,'{}'::jsonb,false),
('marca_de_gork','Marca de Gork','sacred','sacred','/assets/items/sacred/marca_de_gork.png',null,'{}'::jsonb,false),
('joia_da_corrupcao_i','Joia da Corrupção I','jewel','rare','/assets/items/jewels/joia_da_corrupcao_i.png',null,'{}'::jsonb,true),
('joia_da_corrupcao_ii','Joia da Corrupção II','jewel','rare','/assets/items/jewels/joia_da_corrupcao_ii.png',null,'{}'::jsonb,true),
('joia_do_armamento_i','Joia do Armamento I','jewel','rare','/assets/items/jewels/joia_do_armamento_i.png',null,'{}'::jsonb,true),
('joia_do_armamento_ii','Joia do Armamento II','jewel','rare','/assets/items/jewels/joia_do_armamento_ii.png',null,'{}'::jsonb,true),
('joia_da_procrastinacao_i','Joia da Procrastinação I','jewel','rare','/assets/items/jewels/joia_da_procrastinacao_i.png',null,'{}'::jsonb,true),
('joia_da_procrastinacao_ii','Joia da Procrastinação II','jewel','rare','/assets/items/jewels/joia_da_procrastinacao_ii.png',null,'{}'::jsonb,true),
('joia_da_matriz_i','Joia da Matriz I','jewel','rare','/assets/items/jewels/joia_da_matriz_i.png',null,'{}'::jsonb,true),
('joia_da_matriz_ii','Joia da Matriz II','jewel','rare','/assets/items/jewels/joia_da_matriz_ii.png',null,'{}'::jsonb,true),
('joia_da_plenitude_i','Joia da Plenitude I','jewel','rare','/assets/items/jewels/joia_da_plenitude_i.png',null,'{}'::jsonb,true),
('joia_da_plenitude_ii','Joia da Plenitude II','jewel','rare','/assets/items/jewels/joia_da_plenitude_ii.png',null,'{}'::jsonb,true),
('grimorio_da_agua','Grimório da Água','grimoire','rare','/assets/items/grimoires/grimorio_da_agua.png',null,'{}'::jsonb,false),
('grimorio_do_fogo','Grimório do Fogo','grimoire','rare','/assets/items/grimoires/grimorio_do_fogo.png',null,'{}'::jsonb,false),
('grimorio_da_terra','Grimório da Terra','grimoire','rare','/assets/items/grimoires/grimorio_da_terra.png',null,'{}'::jsonb,false),
('grimorio_do_vento','Grimório do Vento','grimoire','rare','/assets/items/grimoires/grimorio_do_vento.png',null,'{}'::jsonb,false),
('grimorio_das_plantas','Grimório das Plantas','grimoire','rare','/assets/items/grimoires/grimorio_das_plantas.png',null,'{}'::jsonb,false),
('grimorio_da_escuridao','Grimório da Escuridão','grimoire','rare','/assets/items/grimoires/grimorio_da_escuridao.png',null,'{}'::jsonb,false),
('grimorio_do_sangue','Grimório do Sangue','grimoire','rare','/assets/items/grimoires/grimorio_do_sangue.png',null,'{}'::jsonb,false),
('grimorio_do_espaco','Grimório do Espaço','grimoire','rare','/assets/items/grimoires/grimorio_do_espaco.png',null,'{}'::jsonb,false),
('grimorio_do_reflexo','Grimório do Reflexo','grimoire','rare','/assets/items/grimoires/grimorio_do_reflexo.png',null,'{}'::jsonb,false),
('escritura_espiritual','Escritura Espiritual','grimoire','rare','/assets/items/grimoires/escritura_espiritual.png',null,'{}'::jsonb,false),
('ferro_bruto','Ferro Bruto','material','common','/assets/items/materials/ferro_bruto.png',null,'{}'::jsonb,true),
('madeira_viva','Madeira Viva','material','common','/assets/items/materials/madeira_viva.png',null,'{}'::jsonb,true),
('couro_sombrio','Couro Sombrio','material','common','/assets/items/materials/couro_sombrio.png',null,'{}'::jsonb,true),
('cristal_de_eter','Cristal de Éter','material','common','/assets/items/materials/cristal_de_eter.png',null,'{}'::jsonb,true),
('fragmento_anomalo','Fragmento Anômalo','material','common','/assets/items/materials/fragmento_anomalo.png',null,'{}'::jsonb,true),
('droga_da_avareza','Droga da Avareza','material','common','/assets/items/materials/droga_da_avareza.png',null,'{}'::jsonb,true),
('droga_da_estranheza','Droga da Estranheza','material','common','/assets/items/materials/droga_da_estranheza.png',null,'{}'::jsonb,true),
('droga_da_fraternidade','Droga da Fraternidade','material','common','/assets/items/materials/droga_da_fraternidade.png',null,'{}'::jsonb,true),
('droga_da_nova_vida','Droga da Nova Vida','material','common','/assets/items/materials/droga_da_nova_vida.png',null,'{}'::jsonb,true),
('medalha_de_apadrinhamento','Medalha de Apadrinhamento','material','common','/assets/items/materials/medalha_de_apadrinhamento.png',null,'{}'::jsonb,true),
('estandarte_de_guerra','Estandarte de Guerra','war','uncommon','/assets/items/war/estandarte_de_guerra.png',null,'{}'::jsonb,false),
('chifre_de_cerco','Chifre de Cerco','war','uncommon','/assets/items/war/chifre_de_cerco.png',null,'{}'::jsonb,false),
('mapa_de_territorio','Mapa de Território','war','uncommon','/assets/items/war/mapa_de_territorio.png',null,'{}'::jsonb,false),
('martelo_de_comando','Martelo de Comando','war','uncommon','/assets/items/war/martelo_de_comando.png',null,'{}'::jsonb,false),
('chave_de_fortaleza','Chave de Fortaleza','war','uncommon','/assets/items/war/chave_de_fortaleza.png',null,'{}'::jsonb,false),
('torre_arcana_portatil','Torre Arcana Portátil','war','uncommon','/assets/items/war/torre_arcana_portatil.png',null,'{}'::jsonb,false),
('racao_de_exercito','Ração de Exército','war','uncommon','/assets/items/war/racao_de_exercito.png',null,'{}'::jsonb,false),
('bandeira_de_conquista','Bandeira de Conquista','war','uncommon','/assets/items/war/bandeira_de_conquista.png',null,'{}'::jsonb,false),
('contrato_de_mercenario','Contrato de Mercenário','war','uncommon','/assets/items/war/contrato_de_mercenario.png',null,'{}'::jsonb,false),
('cofre_familiar','Cofre Familiar','war','uncommon','/assets/items/war/cofre_familiar.png',null,'{}'::jsonb,false)
on conflict (key) do update set name=excluded.name, type=excluded.type, rarity=excluded.rarity, icon_url=excluded.icon_url, visual_key=excluded.visual_key, stackable=excluded.stackable;
