-- Aetherion MVP schema
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  role text default 'player' check (role in ('player','admin')),
  created_at timestamptz default now()
);

create table if not exists public.races (
  id bigint generated by default as identity primary key,
  key text unique not null,
  name text not null,
  description text,
  bonus jsonb default '{}'::jsonb
);

create table if not exists public.families (
  id bigint generated by default as identity primary key,
  key text unique,
  name text unique not null,
  type text default 'main',
  description text,
  origin_region text,
  motto text,
  level int default 1,
  reputation int default 0,
  treasury_gold int default 0,
  parent_family_1 bigint references public.families(id) on delete set null,
  parent_family_2 bigint references public.families(id) on delete set null,
  founder_1 uuid references auth.users(id) on delete set null,
  founder_2 uuid references auth.users(id) on delete set null,
  bonus jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  race_key text references public.races(key),
  class_name text default 'Guerreiro',
  family_id bigint references public.families(id) on delete set null,
  level int default 1,
  xp int default 0,
  gold int default 150,
  hp int default 200,
  mana int default 100,
  stamina int default 130,
  san int default 0,
  strength int default 10,
  defense int default 10,
  agility int default 10,
  magic int default 10,
  vitality int default 10,
  luck int default 10,
  precision int default 10,
  magic_resistance int default 5,
  tenacity int default 5,
  morality_score int default 0,
  current_region text default 'valoria',
  biography text,
  created_at timestamptz default now(),
  unique(user_id)
);

create table if not exists public.family_members (
  id bigint generated by default as identity primary key,
  family_id bigint references public.families(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  character_id bigint references public.characters(id) on delete cascade,
  role text default 'member',
  active boolean default true,
  joined_at timestamptz default now(),
  unique(family_id, user_id)
);

create table if not exists public.family_lineage (
  id bigint generated by default as identity primary key,
  family_id bigint references public.families(id) on delete cascade not null,
  ancestor_family_id bigint references public.families(id) on delete cascade not null,
  percentage int default 50
);

create table if not exists public.marriages (
  id bigint generated by default as identity primary key,
  requester_character_id bigint references public.characters(id) on delete cascade,
  target_character_id bigint references public.characters(id) on delete cascade,
  status text default 'pending',
  created_at timestamptz default now(),
  accepted_at timestamptz
);

create table if not exists public.blood_bonds (
  id bigint generated by default as identity primary key,
  marriage_id bigint references public.marriages(id) on delete cascade,
  bonus jsonb default '{}'::jsonb,
  active bool default true,
  created_at timestamptz default now()
);

create table if not exists public.map_regions (
  id bigint generated by default as identity primary key,
  key text unique not null,
  name text not null,
  zone_type text,
  recommended_level text,
  description text
);

create table if not exists public.territories (
  id bigint generated by default as identity primary key,
  region_id bigint references public.map_regions(id) on delete cascade,
  name text not null,
  type text,
  zone_type text default 'green',
  owner_family_id bigint references public.families(id) on delete set null,
  resource_type text,
  defense_level int default 1,
  danger_level int default 1
);

create table if not exists public.mobs (
  id bigint generated by default as identity primary key,
  region_id bigint references public.map_regions(id) on delete cascade,
  name text not null,
  rarity text default 'common',
  level int default 1,
  hp int default 50,
  attack int default 5,
  defense int default 3,
  sprite_key text,
  loot_table jsonb default '[]'::jsonb
);

create table if not exists public.npcs (
  id bigint generated by default as identity primary key,
  region_id bigint references public.map_regions(id) on delete cascade,
  name text not null,
  sprite_key text,
  dialogue jsonb default '[]'::jsonb,
  interaction_type text default 'dialogue'
);

create table if not exists public.chests (
  id bigint generated by default as identity primary key,
  region_id bigint references public.map_regions(id) on delete cascade,
  chest_type text default 'common',
  name text not null,
  respawn_seconds int default 3600,
  loot_table jsonb default '[]'::jsonb
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  key text unique not null,
  name text not null,
  type text not null,
  rarity text default 'common',
  icon_url text,
  visual_key text,
  stats jsonb default '{}'::jsonb,
  stackable bool default false,
  created_at timestamptz default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade not null,
  item_id bigint references public.items(id) on delete cascade not null,
  quantity int default 1,
  bound_type text default 'loose',
  created_at timestamptz default now(),
  unique(character_id, item_id, bound_type)
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade not null,
  slot text not null,
  item_key text,
  visual_key text,
  updated_at timestamptz default now(),
  unique(character_id, slot)
);

create table if not exists public.professions (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text
);

create table if not exists public.character_professions (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade not null,
  profession_id bigint references public.professions(id) on delete cascade not null,
  level int default 1,
  xp int default 0,
  unique(character_id, profession_id)
);

create table if not exists public.crafting_recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  profession_id bigint references public.professions(id) on delete set null,
  result_item_id bigint references public.items(id) on delete set null,
  required_level int default 1,
  gold_cost int default 0,
  craft_time_seconds int default 60
);

create table if not exists public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.crafting_recipes(id) on delete cascade,
  item_id bigint references public.items(id) on delete cascade,
  quantity int not null
);

create table if not exists public.market_listings (
  id bigint generated by default as identity primary key,
  seller_id uuid references auth.users(id) on delete cascade not null,
  item_id bigint references public.items(id) on delete cascade not null,
  quantity int default 1,
  price_per_unit int not null,
  status text default 'active',
  created_at timestamptz default now(),
  sold_at timestamptz
);

create table if not exists public.market_price_history (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id) on delete cascade not null,
  average_price int not null,
  lowest_price int not null,
  highest_price int not null,
  total_sold int default 0,
  recorded_at timestamptz default now()
);

create table if not exists public.economy_index (
  id bigint generated by default as identity primary key,
  inflation_rate numeric default 0,
  average_basket_price int default 0,
  gold_in_circulation bigint default 0,
  total_market_volume bigint default 0,
  recorded_at timestamptz default now()
);

create table if not exists public.battle_instances (
  id bigint generated by default as identity primary key,
  battle_type text not null,
  zone_type text not null,
  status text default 'active',
  region_id bigint references public.map_regions(id) on delete set null,
  territory_id bigint references public.territories(id) on delete set null,
  started_at timestamptz default now(),
  ended_at timestamptz
);

create table if not exists public.battle_participants (
  id bigint generated by default as identity primary key,
  battle_id bigint references public.battle_instances(id) on delete cascade,
  character_id bigint references public.characters(id) on delete cascade,
  team text default 'solo',
  current_hp int,
  current_mana int,
  current_stamina int,
  current_san int,
  is_down bool default false,
  is_dead bool default false,
  final_damage_done int default 0,
  final_healing_done int default 0
);

create table if not exists public.battle_logs (
  id bigint generated by default as identity primary key,
  battle_id bigint references public.battle_instances(id) on delete set null,
  character_id bigint references public.characters(id) on delete set null,
  action_type text not null,
  result jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.character_deaths (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade,
  battle_id bigint references public.battle_instances(id) on delete set null,
  death_type text not null,
  zone_type text not null,
  killed_by_character_id bigint references public.characters(id) on delete set null,
  lost_gold int default 0,
  lost_items jsonb default '[]'::jsonb,
  wounds jsonb default '[]'::jsonb,
  revived_by text,
  created_at timestamptz default now()
);

create table if not exists public.character_morality (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade unique not null,
  morality_score int default 0,
  goodness_points int default 0,
  evil_points int default 0,
  title text default 'Neutro',
  updated_at timestamptz default now()
);

create table if not exists public.morality_events (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade not null,
  action text not null,
  points int not null,
  alignment text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists public.story_choices (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade not null,
  chapter text not null,
  choice_key text not null,
  choice_label text not null,
  path text not null,
  morality_impact int default 0,
  family_impact int default 0,
  world_impact int default 0,
  created_at timestamptz default now()
);

create table if not exists public.character_chronicles (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade not null,
  event_type text not null,
  title text not null,
  description text not null,
  moral_impact int default 0,
  region text,
  created_at timestamptz default now()
);

create table if not exists public.world_state (
  id bigint generated by default as identity primary key,
  rupture_level int default 0,
  magic_stability int default 100,
  technology_spread int default 0,
  war_intensity int default 0,
  economy_instability int default 0,
  dominant_family_id bigint references public.families(id) on delete set null,
  current_era text default 'Era do Despertar',
  updated_at timestamptz default now()
);

create table if not exists public.family_armies (
  id bigint generated by default as identity primary key,
  family_id bigint references public.families(id) on delete cascade not null,
  name text not null,
  current_territory_id bigint references public.territories(id) on delete set null,
  destination_territory_id bigint references public.territories(id) on delete set null,
  status text default 'idle',
  attack_power int default 0,
  defense_power int default 0,
  magic_power int default 0,
  morale int default 100,
  food_supply int default 100,
  movement_ends_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.army_units (
  id bigint generated by default as identity primary key,
  army_id bigint references public.family_armies(id) on delete cascade not null,
  unit_type text not null,
  quantity int default 0,
  attack int default 1,
  defense int default 1,
  magic int default 0,
  morale int default 10,
  upkeep_gold int default 0
);

create table if not exists public.family_wars (
  id bigint generated by default as identity primary key,
  attacker_family_id bigint references public.families(id) on delete cascade not null,
  defender_family_id bigint references public.families(id) on delete cascade not null,
  territory_id bigint references public.territories(id) on delete set null,
  status text default 'preparing',
  attacker_score int default 0,
  defender_score int default 0,
  winner_family_id bigint references public.families(id) on delete set null,
  starts_at timestamptz,
  ends_at timestamptz,
  war_log jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- RLS
alter table public.profiles enable row level security;
alter table public.characters enable row level security;
alter table public.inventory enable row level security;
alter table public.equipment enable row level security;
alter table public.market_listings enable row level security;
alter table public.character_chronicles enable row level security;
alter table public.character_morality enable row level security;
alter table public.morality_events enable row level security;
alter table public.story_choices enable row level security;

-- Public read tables
alter table public.races enable row level security;
alter table public.families enable row level security;
alter table public.map_regions enable row level security;
alter table public.territories enable row level security;
alter table public.mobs enable row level security;
alter table public.npcs enable row level security;
alter table public.items enable row level security;
alter table public.professions enable row level security;

create policy "profiles own select" on public.profiles for select using (auth.uid() = id);
create policy "profiles own update" on public.profiles for update using (auth.uid() = id);
create policy "profiles own insert" on public.profiles for insert with check (auth.uid() = id);

create policy "characters own select" on public.characters for select using (auth.uid() = user_id);
create policy "characters own update" on public.characters for update using (auth.uid() = user_id);
create policy "characters own insert" on public.characters for insert with check (auth.uid() = user_id);

create policy "inventory own" on public.inventory for select using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));
create policy "equipment own select" on public.equipment for select using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));
create policy "equipment own write" on public.equipment for all using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid())) with check (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));

create policy "market read" on public.market_listings for select using (true);
create policy "market own insert" on public.market_listings for insert with check (auth.uid() = seller_id);

create policy "chronicles own select" on public.character_chronicles for select using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));
create policy "morality own select" on public.character_morality for select using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));
create policy "morality_events own select" on public.morality_events for select using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));
create policy "story own select" on public.story_choices for select using (exists (select 1 from public.characters c where c.id = character_id and c.user_id = auth.uid()));

create policy "public read races" on public.races for select using (true);
create policy "public read families" on public.families for select using (true);
create policy "public read regions" on public.map_regions for select using (true);
create policy "public read territories" on public.territories for select using (true);
create policy "public read mobs" on public.mobs for select using (true);
create policy "public read npcs" on public.npcs for select using (true);
create policy "public read items" on public.items for select using (true);
create policy "public read professions" on public.professions for select using (true);
